name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag zhuzhengqian123/python3-gdal:3.6.3 --tag latest
        docker push --all-tags zhuzhengqian123/python3-gdal
